apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ru5sqd76s-go
  janus-idp.io/tekton: ru5sqd76s-go
  backstage.io/kubernetes-id: ru5sqd76s-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ru5sqd76s-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
